exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_masked_model:
    - FacebookAI/roberta-base

predfpath: /Users/jeong/Projects/cosc426-midterm-b5/predictions/roberta_large.tsv

datafpath: /Users/jeong/Projects/cosc426-midterm-b5/data/data.tsv

resultsfpath: /Users/jeong/Projects/cosc426-midterm-b5/results/roberta_large.tsv

punctuation: previous

save: by_cond

conditions: occupation
