exp: MinimalPair

mode:
  - evaluate
  - analyze

models:
  hf_masked_model:
    - FacebookAI/roberta-base

predfpath: ../cosc426-midterm-b5/predictions/roberta_large.tsv

datafpath: ../cosc426-midterm-b5/data/eval.tsv

resultsfpath: ../cosc426-midterm-b5/results/roberta_large.tsv

punctuation: previous

save: by_cond

conditions: occupation

device: cuda
